name: Test & Coverage CI

on: [push, pull_request]

jobs:
  uvu-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      
      - name: Dependencies
        run: |
          npm i
          npm i -g c8
        
      - name: Tests & Coverage
        run: c8 --all --include 'src/*/*/index.js' npm test
  
      - name: Report
        run: |
          c8 --all --include 'src/*/*/index.js' report --reporter=text-lcov > coverage.lcov
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}