name: UVU CI

on: [push, pull_request]

jobs:
  uvu-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Dependencies
        run: npm i
      
      - name: Tests
        run: npm test
