name: Test & Coverage CI

on: [push, pull_request]

jobs:
  uvu-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodejs }}
      
      - name: Dependencies
        run: |
          npm i
          npm i -g c8
        
      - name: Tests & Coverage
        run: c8 --all --include 'src/*/*/index.js' npm test
  
      - name: Report
        run: |
          c8 report --reporter=text-lcov > coverage.lcov
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}