name: CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Dependencies
        run: npm i
      
      - name: Cypress.io
        uses: cypress-io/github-action@v1.16.1
